import type {
  EpisodePlanLabInput,
  EpisodePlanLabResult,
} from "../domain/index.js";
import { compactStoryOutlineForEpisodePlanLab } from "../domain/index.js";
import type { ChatMessage } from "../llm/types.js";

function compactInput(input: EpisodePlanLabInput): object {
  return {
    project: {
      id: input.project.id,
      title: input.project.title,
      premise: input.project.premise,
      storySetup: input.project.storySetup,
      storyOutline: compactStoryOutlineForEpisodePlanLab(input.project.storyOutline),
      themeBible: input.project.themeBible,
      styleBible: input.project.styleBible,
      themePreset: input.themePreset,
    },
    episodeRequest: {
      episodeId: input.episodeId,
      chapterStart: input.chapterStart,
      chapterEnd: input.chapterEnd,
      targetChapterCount: input.targetChapterCount,
    },
    sourceArcs: input.sourceArcs.map((arc) => ({
      id: arc.id,
      name: arc.name,
      chapterRangeHint: arc.chapterRangeHint,
      arcGoal: arc.arcGoal,
      arcSellingPoint: arc.arcSellingPoint,
      arcHook: arc.arcHook,
      arcPayoff: arc.arcPayoff,
      protagonistArc: arc.protagonistArc,
      supportingCharacterArcs: arc.supportingCharacterArcs,
    })),
    sourceBeats: input.sourceBeats.map((beat) => ({
      id: beat.id,
      arcId: beat.arcId,
      order: beat.order,
      chapterRangeHint: beat.chapterRangeHint,
      beatGoal: beat.beatGoal,
      conflict: beat.conflict,
      expectedChange: beat.expectedChange,
      requiredCharacters: beat.requiredCharacters,
      requiredMemories: beat.requiredMemories,
      payoffPatternIds: beat.payoffPatternIds,
      revealTargets: beat.revealTargets,
      revealItems: beat.revealItems,
      worldFactIds: beat.worldFactIds,
      constraints: beat.constraints,
    })),
    cast: input.cast,
    characters: input.characters.map((character) => ({
      id: character.id,
      name: character.name,
      archetype: character.archetype,
      coreTraits: character.coreTraits,
      desires: character.desires,
      fears: character.fears,
      wounds: character.wounds,
      currentGoals: character.currentGoals,
      emotionalState: character.emotionalState,
      knowledgeBoundary: character.knowledgeBoundary,
      secretsKept: character.secretsKept,
      decisionProfile: character.decisionProfile,
    })),
    worldFacts: input.worldFacts.map((fact) => ({
      id: fact.id,
      category: fact.category,
      title: fact.title,
      description: fact.description,
      scope: fact.scope,
      visibility: fact.visibility,
      relatedCharacterIds: fact.relatedCharacterIds,
      minRevealArc: fact.minRevealArc,
    })),
    existingThreads: input.existingThreads.map((thread) => ({
      id: thread.id,
      threadType: thread.threadType,
      title: thread.title,
      ownerCharacterIds: thread.ownerCharacterIds,
      currentStatus: thread.currentStatus,
      readerQuestion: thread.readerQuestion,
      pressure: thread.pressure,
      stakes: thread.stakes,
      nextUsefulMoves: thread.nextUsefulMoves,
      payoffConditions: thread.payoffConditions,
    })),
  };
}

export function buildEpisodePlanLabMessages(input: EpisodePlanLabInput): ChatMessage[] {
  return [
    {
      role: "system",
      content: [
        "Task: build an episode-level narrative container and extract an episode chapter plan set.",
        "This is NOT the old beat-to-one-chapter planner.",
        "Core principle:",
        "- First create a strong episode_outline: an external event container with factions, rules, pressure, escalation, and reader promises.",
        "- Then create character_threads: each thread must collide with the episode container, not run as isolated biography.",
        "- Every character_thread must include characterPayload. This is not biography; it is the reader-facing role engine: hookLabel, surfaceMask, coreDrive, innerContradiction, competenceProof, vulnerabilityCost, readerDesireHook, relationshipLeverage, iconicBehavior, oocGuard.",
        "- Then create world_rule_tracks: world rules must create plot pressure and reader curiosity, not exposition dumps.",
        "- Then create event_pool: concrete writable events generated from container + character thread + world rule collisions.",
        "- Finally create episode_chapter_plan_set by selecting and sequencing events from the event_pool.",
        "",
        "Reader lens:",
        "- Optimize for mainstream serialized webnovel readers.",
        "- Character benchmark lesson from hot Fanqie-style openings: readers remember characters through a sharp label + immediate competence proof + visible contradiction under pressure + repeatable iconic behavior. Do not only say a character is smart/cold/loyal; make the first 1-3 events prove it.",
        "- characterPayload.hookLabel should be short and sticky, usually 3-10 Chinese characters or 2-5 English words.",
        "- Main character must have a visible unfair advantage or extreme coping style. Rival/antagonist must create social pressure and retaliatory movement. Ally/love-interest/witness must have a cost for choosing the protagonist.",
        "- Every chapter plan needs a hook, concrete event, collision, turn/choice, visible payoff, cost/complication, and end hook.",
        "- Avoid vague summaries like 'relationship develops' or 'worldbuilding is revealed'. Make it stageable.",
        "- Opening-episode benchmark lesson from hot serialized webnovels: the first 10-20 chapters should usually form a named container with a public rule/deadline, fast resource or ability validation, repeated visible wins/setbacks, social pressure, and a gate into the larger world.",
        "- Do not make early chapters only explain premise. Convert premise into tests, exams, missions, meetings, chases, duels, uploads, public confrontations, or transactional deadlines.",
        "- Every event_pool item must include genrePayload.readerSettlement. This is the commercial settlement ledger: immediateReward, newDebtOrThreat, socialReaction, nextGate.",
        "- Add at least one specialized genrePayload field where relevant: statusGate for institution/status openings, ownershipTransfer for resource-stealing openings, lieState for deception/romance openings, abilityBudget for power-limit openings.",
        "- If project.themePreset is present, treat it as the primary experimental theme. Use the original project only as style/reference context.",
        "- If project.themePreset.requiredGenrePayload lists fields, use those fields repeatedly across event_pool.",
        "- If the given project theme lacks a strong commercial settlement loop, strengthen the episode container around one: status validation, resource ownership transfer, deception deadline, or ability budget.",
        "- event_pool.eventType must vary with the actual event. Do not label every event as test.",
        "- Allowed eventType values: departure, discovery, attempt, encounter, confrontation, crisis, arrival, rule_pressure, test, duel, betrayal, reveal, setback, payoff, invasion, aftermath.",
        "- event_pool.stage should name a concrete phase of the external event container, not generic labels like pressure/resolve/collision.",
        "- Keep time continuity strict. Do not confuse whether a wedding/exam/deadline is today, tomorrow, already happening, or still approaching.",
        "- Do not write prose.",
        "",
        "Hard constraints:",
        "- Output valid JSON only.",
        "- Use exactly these top-level keys: episode_outline, character_threads, world_rule_tracks, event_pool, episode_chapter_plan_set, notes.",
        "- episode_chapter_plan_set.plans length must equal targetChapterCount.",
        "- Each plan must cite mainEventIds from event_pool.",
        "- Every event should cite at least one character thread or world rule track when possible.",
        "- Keep JSON keys and id tokens in English. Semantic text may be concise Chinese.",
        "- Treat source beats as reference material, not as chapter slices.",
      ].join("\n"),
    },
    {
      role: "user",
      content: JSON.stringify(compactInput(input), null, 2),
    },
  ];
}

export const episodePlanLabResultSchema: EpisodePlanLabResult = {
  episode_outline: {
    id: "episode-1-8",
    title: "string",
    chapterRange: {
      start: 1,
      end: 8,
    },
    sourceArcIds: ["arc-1"],
    sourceBeatIds: ["beat-1"],
    externalEventContainer: "string",
    centralPressure: "string",
    factions: ["string"],
    readerPromises: ["string"],
    escalationLadder: ["string"],
    doNotResolveYet: ["string"],
  },
  character_threads: [
    {
      id: "thread-character-1",
      characterId: "character-id",
      title: "string",
      readerQuestion: "string",
      startingPressure: "string",
      desiredTurn: "string",
      collisionWithEventContainer: "string",
      characterPayload: {
        hookLabel: "string",
        surfaceMask: "string",
        coreDrive: "string",
        innerContradiction: "string",
        competenceProof: "string",
        vulnerabilityCost: "string",
        readerDesireHook: "string",
        relationshipLeverage: "string",
        iconicBehavior: "string",
        oocGuard: "string",
      },
      mustTouchChapters: [1],
      payoffExpectation: "string",
    },
  ],
  world_rule_tracks: [
    {
      id: "world-rule-track-1",
      worldFactIds: ["world-fact-id"],
      title: "string",
      rulePressure: "string",
      howReadersLearnIt: "string",
      plotFunction: "string",
      revealSteps: [
        {
          chapterNumber: 1,
          step: "string",
        },
      ],
      forbiddenInfodump: "string",
    },
  ],
  event_pool: [
    {
      id: "event-1",
      stage: "string",
      eventType: "test",
      oneLine: "string",
      involvedCharacterIds: ["character-id"],
      threadIds: ["thread-character-1"],
      worldRuleTrackIds: ["world-rule-track-1"],
      readerPayoff: "string",
      costOrConsequence: "string",
      genrePayload: {
        ownershipTransfer: {
          expectedOwner: "string",
          actualOwner: "string",
          asset: "string",
          retaliationCreated: "string",
        },
        readerSettlement: {
          immediateReward: "string",
          newDebtOrThreat: "string",
          socialReaction: "string",
          nextGate: "string",
        },
      },
      suggestedChapter: 1,
    },
  ],
  episode_chapter_plan_set: {
    episodeId: "episode-1-8",
    plans: [
      {
        chapterNumber: 1,
        title: "string",
        chapterMode: "pressure",
        payoffType: "information_reveal",
        mainEventIds: ["event-1"],
        primaryCharacterThreadId: "thread-character-1",
        supportingThreadIds: ["thread-character-2"],
        worldRuleTrackIds: ["world-rule-track-1"],
        chapterGoal: "string",
        openingHook: "string",
        centralCollision: "string",
        forcedChoiceOrTurn: "string",
        visiblePayoff: "string",
        costOrComplication: "string",
        endHook: "string",
        writerBrief: "string",
        disallowedMoves: ["string"],
      },
    ],
  },
  notes: ["string"],
} as unknown as EpisodePlanLabResult;
